# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppPokedexCards' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppPokedexCards

pod 'Firebase/Firestone'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

  target 'AppPokedexCardsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppPokedexCardsUITests' do
    # Pods for testing
  end

end
